import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { expect, test } from "@playwright/test";
import { OCR_ASSETS, OCR_ASSET_LIST } from "../../src/lib/ocr/assets.generated";
import {
  OCR_ASSET_ROUTE,
  OCR_CACHE_NAME,
  OCR_CHAR_WHITELIST,
  OCR_INIT_CONFIG,
  OCR_LANG,
  OCR_OEM,
  OCR_PARAMS,
} from "../../src/lib/ocr/constants";
import { toOcrLine, tesseractOptions, tesseractPaths } from "../../src/lib/ocr/runtime";
import type { TesseractPage } from "../../src/lib/ocr/runtime";

/**
 * The self-hosted OCR engine, against the build the suite actually serves.
 *
 * Two things can only be checked here. The precache manifest is generated by workbox at
 * build time — S5 addendum §3's landmine is the 3.9 MB core matching the shell's `.js`
 * glob — and the three CDN paths tesseract.js falls back to are only reachable from a
 * browser: no unit test can tell whether the engine that runs is the one this repo
 * shipped.
 *
 * On this tree the oversized-asset case fails the build outright rather than dropping the
 * file quietly (`vite-plugin-pwa` 1.3.0), so the assertion below is driven red by raising
 * `maximumFileSizeToCacheInBytes` past 3.9 MB and dropping `globIgnores` — which is
 * exactly the "fix" that would ship 4.5 MB in every install.
 */

const DIST = resolve(import.meta.dirname, "../../dist");
const ORIGIN = "https://localhost:4173";

/** Workbox's default `maximumFileSizeToCacheInBytes`, and the size of the silence. */
const WORKBOX_DEFAULT_MAX_BYTES = 2 * 1024 * 1024;

/** A GM paint code, and the token §5's crop box catches beside it on the same label line. */
const CODE = "WA8555";
const LABEL_LINE = `PNT ${CODE}`;

/** The shell's glob, from both Vite configs. */
const SHELL_EXTENSIONS = [".js", ".css", ".html", ".svg", ".png", ".woff2"];

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

/** The URLs workbox wrote into `precacheAndRoute`, read out of the minified worker. */
function precacheManifest(): string[] {
  const sw = readFileSync(join(DIST, "sw.js"), "utf8");
  expect(sw, "the service worker precaches nothing at all").toContain("precacheAndRoute([");
  const urls = [...sw.matchAll(/\{url:"([^"]+)",revision:/g)].map((match) => match[1]);
  expect(urls.length, "no precache entry was found in sw.js").toBeGreaterThan(0);
  return urls;
}

test("the OCR engine ships, and none of it is in the precache manifest", () => {
  // It is on disk, all four files, at the sizes the runtime verifies against.
  for (const spec of OCR_ASSET_LIST) {
    expect(statSync(join(DIST, "ocr", spec.file)).size, spec.file).toBe(spec.bytes);
  }

  const manifest = precacheManifest();
  expect(manifest.filter((url) => url.includes("ocr/"))).toEqual([]);

  // And the shell is whole: every file the glob matches, outside `ocr/`, is precached.
  // Keeping the engine out is only half of it; the half that goes wrong quietly is
  // keeping something else out with it.
  const precached = new Set(manifest);
  const shell = walk(DIST)
    .map((path) => relative(DIST, path))
    .filter((path) => SHELL_EXTENSIONS.some((extension) => path.endsWith(extension)))
    .filter((path) => !path.startsWith("ocr/"))
    .filter((path) => path !== "sw.js" && !path.startsWith("workbox-"));
  for (const path of shell) {
    expect(precached, `${path} matches the shell glob and was not precached`).toContain(path);
  }

  // Nothing precached is near the size that gets dropped in silence.
  for (const url of manifest) {
    expect(statSync(join(DIST, url)).size, url).toBeLessThan(WORKBOX_DEFAULT_MAX_BYTES);
  }
});

test("the service worker serves the engine from Cache Storage instead", () => {
  const sw = readFileSync(join(DIST, "sw.js"), "utf8");

  // One route, whole: the pattern `constants.ts` defines, a cache-first handler, and the
  // bucket the warm-up writes into — matched as one string rather than three, because a
  // cache name that merely *contains* the right one is a different cache and the engine
  // would be downloaded twice and served from neither offline.
  //
  // What the pattern matches is `constants.test.ts`'s to say. That this is the pattern
  // and this is the bucket that shipped is this file's, because nothing else in the gate
  // reads the generated worker.
  //
  // Without this route the lazily fetched engine is online only, which is the same
  // failure precaching it would have caused.
  const route =
    `registerRoute(${String(OCR_ASSET_ROUTE)},` +
    `new e.CacheFirst({cacheName:${JSON.stringify(OCR_CACHE_NAME)},`;
  expect(sw).toContain(route);
});

/** A crisp single line, drawn at the size a crop box would give. */
function drawPaintCode(code: string): string {
  const canvas = document.createElement("canvas");
  canvas.width = 700;
  canvas.height = 120;
  const ctx = canvas.getContext("2d")!;
  ctx.fillStyle = "#fff";
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = "#000";
  ctx.font = "72px monospace";
  ctx.fillText(code, 30, 88);
  return canvas.toDataURL("image/png");
}

interface TesseractWorkerHandle {
  setParameters: (params: Record<string, string>) => Promise<unknown>;
  recognize: (
    image: string,
    options: Record<string, unknown>,
    output: Record<string, boolean>,
  ) => Promise<{ data: TesseractPage }>;
  terminate: () => Promise<void>;
}

interface TesseractModule {
  createWorker: (
    langs: string,
    oem: number,
    options: Record<string, unknown>,
    config: Record<string, string>,
  ) => Promise<TesseractWorkerHandle>;
}

/**
 * Loads the shipped runtime and reads one rendered line, in the page.
 *
 * Every setting comes from `src/lib/ocr/constants.ts` rather than being retyped here (§7
 * item 5). It was retyped, and the copy went stale the moment `OCR_WHITELIST_PARAM` gave
 * the engine a space: this file went on certifying that the engine reads a paint code
 * under a configuration the app had stopped shipping.
 */
async function readLine(
  page: import("@playwright/test").Page,
  options: Record<string, unknown>,
  text: string,
  params: Record<string, string>,
): Promise<TesseractPage> {
  return page.evaluate(
    async ({ options: workerOptions, runtimeUrl, source, text: line, params: setParams, init }) => {
      const draw = new Function(`return (${source})`)() as (code: string) => string;
      const imported = (await import(/* @vite-ignore */ runtimeUrl)) as {
        default?: TesseractModule;
        createWorker?: TesseractModule["createWorker"];
      };
      const tesseract: TesseractModule =
        typeof imported.createWorker === "function"
          ? (imported as TesseractModule)
          : imported.default!;

      const worker = await tesseract.createWorker(init.lang, init.oem, workerOptions, init.config);
      await worker.setParameters(setParams);
      const { data } = await worker.recognize(draw(line), {}, { text: true, blocks: true });
      await worker.terminate();
      // Projected to exactly `TesseractPage`, because the engine's own tree carries handles
      // that do not cross the bridge — and because this is the shape `toOcrLine` reads.
      return {
        text: data.text,
        confidence: data.confidence,
        blocks: (data.blocks ?? []).map((block) => ({
          paragraphs: (block.paragraphs ?? []).map((paragraph) => ({
            lines: (paragraph.lines ?? []).map((each) => ({
              words: (each.words ?? []).map((word) => ({
                symbols: (word.symbols ?? []).map((symbol) => ({
                  text: symbol.text,
                  confidence: symbol.confidence,
                })),
              })),
            })),
          })),
        })),
      } satisfies TesseractPage;
    },
    {
      options,
      runtimeUrl: `${ORIGIN}/ocr/${OCR_ASSETS.runtime.file}`,
      source: drawPaintCode.toString(),
      text,
      params,
      init: { lang: OCR_LANG, oem: OCR_OEM, config: { ...OCR_INIT_CONFIG } },
    },
  );
}

const PINNED_OPTIONS = (): Record<string, unknown> =>
  tesseractOptions(
    tesseractPaths(`${ORIGIN}/`, {
      worker: OCR_ASSETS.worker.file,
      core: OCR_ASSETS.core.file,
    }),
  );

test("reads a paint code with the pinned assets, and asks no CDN for anything", async ({
  page,
}) => {
  test.setTimeout(120_000);

  // Not "we saw no request to a CDN" — every third-party host is dead for this page, so a
  // fallback to `cdn.jsdelivr.net` fails the recognition below rather than passing quietly.
  const offOrigin: string[] = [];
  await page.context().route("**/*", (route) => {
    const url = new URL(route.request().url());
    if (url.origin === ORIGIN) return route.continue();
    offOrigin.push(url.href);
    return route.abort();
  });

  await page.goto("/#/scan");

  const result = await readLine(page, PINNED_OPTIONS(), "WA8555", { ...OCR_PARAMS });

  expect(offOrigin, "the engine asked a third party for something").toEqual([]);
  expect(result.text.trim()).toBe("WA8555");
  expect(result.confidence).toBeGreaterThan(50);
});

/**
 * The measurement `OCR_WHITELIST_PARAM` stands on, made rather than quoted.
 *
 * `constants.ts` carries a figure taken by hand in Chromium — one word at page confidence
 * 0 without the space, two words at 91 with it — and until now the gate reproduced none of
 * it. `constants.test.ts` and `runtime.test.ts` pin only that the space *is* in the
 * parameter and that `toOcrLine` splits a page that already has two words in it; both stay
 * green with the space put back, on a fabricated page, so the reason for the space was a
 * sentence in a docblock and nothing else. This is the only test in the suite that can
 * make it, because only a browser can run the engine (§13.7 keeps the accuracy question
 * itself human: this says the whitelist changes the segmentation, never that a real
 * sticker reads).
 *
 * `PNT WA8555` is the shape §5's crop box actually produces — a box a gloved hand can aim
 * with catches the token beside the code — and the word boundary between them is the whole
 * of §5's "pattern step". Read through `toOcrLine`, the repo's own function, on the real
 * engine's real output.
 */
test("the space in the whitelist is what buys §5's word boundaries", async ({ page }) => {
  test.setTimeout(180_000);
  await page.goto("/#/scan");
  const options = PINNED_OPTIONS();

  const shipped = toOcrLine(await readLine(page, options, LABEL_LINE, { ...OCR_PARAMS }));
  expect(shipped.tokens.map((token) => token.text)).toEqual(["PNT", CODE]);
  expect(shipped.text).toBe(`PNT ${CODE}`);
  expect(shipped.confidence).toBeGreaterThan(50);
  // The separator the engine was given never reaches a proposal. `chars` is built from the
  // tokens and not from `text`, which is the one place the gap survives — building it from
  // the text instead is the refactor that puts a space in the middle of a paint code.
  expect(shipped.chars.map((char) => char.char).join("")).toBe(`PNT${CODE}`);

  // The same line, the same engine, the same everything except the separator the engine is
  // allowed to see. Telling it the gap it can see cannot exist costs the boundary the vote
  // is taken over — and both tokens are then one candidate no person can pick between.
  const withheld = toOcrLine(
    await readLine(page, options, LABEL_LINE, {
      ...OCR_PARAMS,
      tessedit_char_whitelist: OCR_CHAR_WHITELIST,
    }),
  );
  expect(withheld.tokens).toHaveLength(1);
  expect(withheld.confidence).toBeLessThan(shipped.confidence);
});
