import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { expect, test } from "@playwright/test";
import { OCR_ASSETS, OCR_ASSET_LIST } from "../../src/lib/ocr/assets.generated";
import { OCR_ASSET_ROUTE, OCR_CACHE_NAME } from "../../src/lib/ocr/constants";
import { tesseractOptions, tesseractPaths } from "../../src/lib/ocr/runtime";

/**
 * The self-hosted OCR engine, against the build the suite actually serves.
 *
 * Two things can only be checked here. The precache manifest is generated by workbox at
 * build time — S5 addendum §3's landmine is the 3.9 MB core matching the shell's `.js`
 * glob — and the three CDN paths tesseract.js falls back to are only reachable from a
 * browser: no unit test can tell whether the engine that runs is the one this repo
 * shipped.
 *
 * On this tree the oversized-asset case fails the build outright rather than dropping the
 * file quietly (`vite-plugin-pwa` 1.3.0), so the assertion below is driven red by raising
 * `maximumFileSizeToCacheInBytes` past 3.9 MB and dropping `globIgnores` — which is
 * exactly the "fix" that would ship 4.5 MB in every install.
 */

const DIST = resolve(import.meta.dirname, "../../dist");
const ORIGIN = "https://localhost:4173";

/** Workbox's default `maximumFileSizeToCacheInBytes`, and the size of the silence. */
const WORKBOX_DEFAULT_MAX_BYTES = 2 * 1024 * 1024;

/** The shell's glob, from both Vite configs. */
const SHELL_EXTENSIONS = [".js", ".css", ".html", ".svg", ".png", ".woff2"];

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

/** The URLs workbox wrote into `precacheAndRoute`, read out of the minified worker. */
function precacheManifest(): string[] {
  const sw = readFileSync(join(DIST, "sw.js"), "utf8");
  expect(sw, "the service worker precaches nothing at all").toContain("precacheAndRoute([");
  const urls = [...sw.matchAll(/\{url:"([^"]+)",revision:/g)].map((match) => match[1]);
  expect(urls.length, "no precache entry was found in sw.js").toBeGreaterThan(0);
  return urls;
}

test("the OCR engine ships, and none of it is in the precache manifest", () => {
  // It is on disk, all four files, at the sizes the runtime verifies against.
  for (const spec of OCR_ASSET_LIST) {
    expect(statSync(join(DIST, "ocr", spec.file)).size, spec.file).toBe(spec.bytes);
  }

  const manifest = precacheManifest();
  expect(manifest.filter((url) => url.includes("ocr/"))).toEqual([]);

  // And the shell is whole: every file the glob matches, outside `ocr/`, is precached.
  // Keeping the engine out is only half of it; the half that goes wrong quietly is
  // keeping something else out with it.
  const precached = new Set(manifest);
  const shell = walk(DIST)
    .map((path) => relative(DIST, path))
    .filter((path) => SHELL_EXTENSIONS.some((extension) => path.endsWith(extension)))
    .filter((path) => !path.startsWith("ocr/"))
    .filter((path) => path !== "sw.js" && !path.startsWith("workbox-"));
  for (const path of shell) {
    expect(precached, `${path} matches the shell glob and was not precached`).toContain(path);
  }

  // Nothing precached is near the size that gets dropped in silence.
  for (const url of manifest) {
    expect(statSync(join(DIST, url)).size, url).toBeLessThan(WORKBOX_DEFAULT_MAX_BYTES);
  }
});

test("the service worker serves the engine from Cache Storage instead", () => {
  const sw = readFileSync(join(DIST, "sw.js"), "utf8");

  // One route, whole: the pattern `constants.ts` defines, a cache-first handler, and the
  // bucket the warm-up writes into — matched as one string rather than three, because a
  // cache name that merely *contains* the right one is a different cache and the engine
  // would be downloaded twice and served from neither offline.
  //
  // What the pattern matches is `constants.test.ts`'s to say. That this is the pattern
  // and this is the bucket that shipped is this file's, because nothing else in the gate
  // reads the generated worker.
  //
  // Without this route the lazily fetched engine is online only, which is the same
  // failure precaching it would have caused.
  const route =
    `registerRoute(${String(OCR_ASSET_ROUTE)},` +
    `new e.CacheFirst({cacheName:${JSON.stringify(OCR_CACHE_NAME)},`;
  expect(sw).toContain(route);
});

/** A crisp single line of a real paint code, drawn at the size a crop box would give. */
function drawPaintCode(code: string): string {
  const canvas = document.createElement("canvas");
  canvas.width = 600;
  canvas.height = 120;
  const ctx = canvas.getContext("2d")!;
  ctx.fillStyle = "#fff";
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = "#000";
  ctx.font = "72px monospace";
  ctx.fillText(code, 30, 88);
  return canvas.toDataURL("image/png");
}

interface TesseractWorkerHandle {
  setParameters: (params: Record<string, string>) => Promise<unknown>;
  recognize: (
    image: string,
    options: Record<string, unknown>,
    output: Record<string, boolean>,
  ) => Promise<{ data: { text: string; confidence: number } }>;
  terminate: () => Promise<void>;
}

interface TesseractModule {
  createWorker: (
    langs: string,
    oem: number,
    options: Record<string, unknown>,
    config: Record<string, string>,
  ) => Promise<TesseractWorkerHandle>;
}

/** Loads the shipped runtime and reads one rendered paint code, in the page. */
async function readPaintCode(
  page: import("@playwright/test").Page,
  options: Record<string, unknown>,
): Promise<{ text: string; confidence: number }> {
  return page.evaluate(
    async ({ options: workerOptions, runtimeUrl, source }) => {
      const draw = new Function(`return (${source})`)() as (code: string) => string;
      const imported = (await import(/* @vite-ignore */ runtimeUrl)) as {
        default?: TesseractModule;
        createWorker?: TesseractModule["createWorker"];
      };
      const tesseract: TesseractModule =
        typeof imported.createWorker === "function"
          ? (imported as TesseractModule)
          : imported.default!;

      const worker = await tesseract.createWorker("eng", 1, workerOptions, {
        load_system_dawg: "false",
        load_freq_dawg: "false",
      });
      await worker.setParameters({
        tessedit_char_whitelist: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-",
        tessedit_pageseg_mode: "7",
      });
      const { data } = await worker.recognize(draw("WA8555"), {}, { text: true, blocks: true });
      await worker.terminate();
      return { text: data.text.trim(), confidence: data.confidence };
    },
    {
      options,
      runtimeUrl: `${ORIGIN}/ocr/${OCR_ASSETS.runtime.file}`,
      source: drawPaintCode.toString(),
    },
  );
}

const PINNED_OPTIONS = (): Record<string, unknown> =>
  tesseractOptions(
    tesseractPaths(`${ORIGIN}/`, {
      worker: OCR_ASSETS.worker.file,
      core: OCR_ASSETS.core.file,
    }),
  );

test("reads a paint code with the pinned assets, and asks no CDN for anything", async ({
  page,
}) => {
  test.setTimeout(120_000);

  // Not "we saw no request to a CDN" — every third-party host is dead for this page, so a
  // fallback to `cdn.jsdelivr.net` fails the recognition below rather than passing quietly.
  const offOrigin: string[] = [];
  await page.context().route("**/*", (route) => {
    const url = new URL(route.request().url());
    if (url.origin === ORIGIN) return route.continue();
    offOrigin.push(url.href);
    return route.abort();
  });

  await page.goto("/#/scan");

  const result = await readPaintCode(page, PINNED_OPTIONS());

  expect(offOrigin, "the engine asked a third party for something").toEqual([]);
  expect(result.text).toBe("WA8555");
  expect(result.confidence).toBeGreaterThan(50);
});
