/**
 * Generated by `bun run build:ocr` — do not edit.
 *
 * The size and digest of every file in `public/ocr/`. The runtime checks a lazily fetched
 * asset against these before it is used and before it is cached: a truncated 3.9 MB
 * download over a dropping connection is otherwise a Cache Storage entry that is wrong
 * forever, and a model carrying a dictionary is wrong in the direction N2 exists to
 * prevent. Knowing the sizes up front is also what lets the download be shown as a size
 * before it is started rather than as a spinner.
 */
export interface OcrAssetSpec {
  /** File name under the app's `ocr/` directory. */
  readonly file: string;
  readonly bytes: number;
  readonly sha256: string;
}

export const OCR_ASSETS = {
  runtime: {
    file: "tesseract.esm.min.js",
    bytes: 63220,
    sha256: "64871d76c75609fd5413b88a8171e2ef40deedd77d5875ba23df104b2d05eb29",
  },
  worker: {
    file: "worker.min.js",
    bytes: 111307,
    sha256: "576b7df7e3393e137e51849357c9adb53fe7ac1bb69bfa06cf3d61520f182c6d",
  },
  core: {
    file: "tesseract-core-simd-lstm.wasm.js",
    bytes: 3899470,
    sha256: "dc885035f7234f7ea1ba4450da5455468746df28a2deb1fc9e474d487037bead",
  },
  model: {
    file: "eng.traineddata",
    bytes: 409234,
    sha256: "b2111851cd6036f42297df1f1ddf946985f8656a73600f3b92411c32f691cab0",
  },
} as const satisfies Record<string, OcrAssetSpec>;

/** Fetch order: everything the worker needs before the model it will read. */
export const OCR_ASSET_LIST: readonly OcrAssetSpec[] = [
  OCR_ASSETS.runtime,
  OCR_ASSETS.worker,
  OCR_ASSETS.core,
  OCR_ASSETS.model,
];

/** What "first OCR use" costs on the wire, before any transfer encoding. */
export const OCR_TOTAL_BYTES = 4483231;
