/**
 * §4.5 WMI: region, country and the seeded manufacturer. Coarse by design — vPIC
 * `Manufacturer` and `PlantCountry` are authoritative once the catalog decode lands
 * (§4.7). Pure: no DOM, no React, no I/O (P3); the seed is a compiled-in constant.
 */
import type { Region } from "./types";
import seed from "./wmi-seed.json";

interface WmiSeedEntry {
  manufacturer: string;
  make?: string;
}

/**
 * §4.5 verbatim: `A–H` Africa · `J–R` Asia · `S–Z` Europe · `1–5` North America ·
 * `6–7` Oceania · `8–9` South America. The ranges are spelled out over the §4.1
 * alphabet so `I`, `O` and `Q` cannot slip in through a character-code comparison.
 * They cover 32 of the 33 characters: `0` is in no range and has no region (D06).
 */
export const REGION_RANGES: readonly (readonly [chars: string, region: Region])[] = [
  ["ABCDEFGH", "Africa"],
  ["JKLMNPR", "Asia"],
  ["STUVWXYZ", "Europe"],
  ["12345", "North America"],
  ["67", "Oceania"],
  ["89", "South America"],
];

const REGION_BY_FIRST_CHAR = new Map<string, Region>(
  REGION_RANGES.flatMap(([chars, region]) => [...chars].map((c): [string, Region] => [c, region])),
);

/** §4.5. Any other first character shows the region alone. */
const COUNTRY_BY_FIRST_CHAR = new Map<string, string>([
  ["1", "United States"],
  ["2", "Canada"],
  ["3", "Mexico"],
  ["4", "United States"],
  ["5", "United States"],
  ["J", "Japan"],
  ["L", "China"],
  ["W", "Germany"],
]);

/** Generated by `bun run seed:wmi` (§4.5, D09). Empty until that script has run. */
const WMI_SEED = seed as Readonly<Record<string, WmiSeedEntry>>;

export function wmiFromVin(vin: string): string {
  return vin.slice(0, 3);
}

export function regionFromVin(vin: string): Region | null {
  return REGION_BY_FIRST_CHAR.get(vin.charAt(0)) ?? null;
}

export function countryFromVin(vin: string): string | null {
  return COUNTRY_BY_FIRST_CHAR.get(vin.charAt(0)) ?? null;
}

export function manufacturerFromWmi(wmi: string): string | null {
  // Cast because the index signature is not `| undefined` without noUncheckedIndexedAccess;
  // optional chaining also absorbs `Object.prototype` keys such as `constructor`.
  const entry = WMI_SEED[wmi] as WmiSeedEntry | undefined;
  return entry?.manufacturer ?? null;
}
